//
//  RegisterViewController.swift
//  HedefYks
//
//  Created by K. Sergen ÖZEL on 21.03.2021.
//

import UIKit
import Firebase

class RegisterViewController: UIViewController, UITextFieldDelegate {

    @IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var surnameTextLabel: UITextField!
    @IBOutlet weak var emailTextLabel: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        let gestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(hideKeyboard))
        view.addGestureRecognizer(gestureRecognizer)
        
        self.nameTextField.delegate = self
        self.surnameTextLabel.delegate = self
        self.emailTextLabel.delegate = self
        self.passwordTextField.delegate = self
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        self.switchBasedNextTextField(textField)
        return true
    }
    
    private func switchBasedNextTextField(_ textField: UITextField) {
        switch textField {
        case self.nameTextField:
            self.surnameTextLabel.becomeFirstResponder()
        case self.surnameTextLabel:
            self.emailTextLabel.becomeFirstResponder()
        case self.emailTextLabel:
            self.passwordTextField.becomeFirstResponder()
        default:
            self.passwordTextField.resignFirstResponder()
        }
    }
    
    @objc func hideKeyboard() {
        view.endEditing(true)
    }
    
    @IBAction func registerButtonClicked(_ sender: UIButton) {
        if nameTextField.text != "" && surnameTextLabel.text != "" && emailTextLabel.text != "" && passwordTextField.text != "" {
            Auth.auth().createUser(withEmail: emailTextLabel.text!, password: passwordTextField.text!) { (auth, error) in
                if error != nil {
                    self.makeAlert(title: "Hata", message: error?.localizedDescription ?? "Bir hata oluştu. Lütfen tekrar deneyin.")
                } else {
                    let fireStore = Firestore.firestore()
                    let userDict = [
                        "ad" : self.nameTextField.text!,
                        "soyad" : self.surnameTextLabel.text!,
                        "email" : self.emailTextLabel.text!,
                        "TYT Yüzdeler" : [
                            "Türkçe":"0",
                            "Tarih":"0",
                            "Coğrafya":"0",
                            "Felsefe":"0",
                            "Din Kültürü":"0",
                            "Matematik":"0",
                            "Geometri":"0",
                            "Fizik":"0",
                            "Kimya":"0",
                            "Biyoloji":"0",
                        ],
                        "AYT Yüzdeler" : [
                            "Edebiyat":"0",
                            "Tarih":"0",
                            "Coğrafya":"0",
                            "Felsefe":"0",
                            "Din Kültürü":"0",
                            "Matematik":"0",
                            "Geometri":"0",
                            "Fizik":"0",
                            "Kimya":"0",
                            "Biyoloji":"0",
                        ],
                        "TYT Ders Süre" : [
                            "Türkçe":"00:00:00",
                            "Tarih":"00:00:00",
                            "Coğrafya":"00:00:00",
                            "Felsefe":"00:00:00",
                            "Din Kültürü":"00:00:00",
                            "Matematik":"00:00:00",
                            "Geometri":"00:00:00",
                            "Fizik":"00:00:00",
                            "Kimya":"00:00:00",
                            "Biyoloji":"00:00:00",
                        ],
                        "TYT Ders Soru" : [
                            "Türkçe":"0",
                            "Tarih":"0",
                            "Coğrafya":"0",
                            "Felsefe":"0",
                            "Din Kültürü":"0",
                            "Matematik":"0",
                            "Geometri":"0",
                            "Fizik":"0",
                            "Kimya":"0",
                            "Biyoloji":"0",
                        ],
                        "TYT Ders Yüzde" : [
                            "Türkçe":"0%",
                            "Tarih":"0%",
                            "Coğrafya":"0%",
                            "Felsefe":"0%",
                            "Din Kültürü":"0%",
                            "Matematik":"0%",
                            "Geometri":"0%",
                            "Fizik":"0%",
                            "Kimya":"0%",
                            "Biyoloji":"0%",
                        ],
                        "AYT Ders Süre" : [
                            "Edebiyat":"00:00:00",
                            "Tarih":"00:00:00",
                            "Coğrafya":"00:00:00",
                            "Felsefe":"00:00:00",
                            "Din Kültürü":"00:00:00",
                            "Matematik":"00:00:00",
                            "Geometri":"00:00:00",
                            "Fizik":"00:00:00",
                            "Kimya":"00:00:00",
                            "Biyoloji":"00:00:00",
                        ],
                        "AYT Ders Soru" : [
                            "Edebiyat":"0",
                            "Tarih":"0",
                            "Coğrafya":"0",
                            "Felsefe":"0",
                            "Din Kültürü":"0",
                            "Matematik":"0",
                            "Geometri":"0",
                            "Fizik":"0",
                            "Kimya":"0",
                            "Biyoloji":"0",
                        ],
                        "AYT Ders Yüzde" : [
                            "Edebiyat":"0%",
                            "Tarih":"0%",
                            "Coğrafya":"0%",
                            "Felsefe":"0%",
                            "Din Kültürü":"0%",
                            "Matematik":"0%",
                            "Geometri":"0%",
                            "Fizik":"0%",
                            "Kimya":"0%",
                            "Biyoloji":"0%",
                        ],
                        "YDT Ders Süre" : [
                            "Almanca":"00:00:00",
                            "Arapça":"00:00:00",
                            "Fransızca":"00:00:00",
                            "İngilizce":"00:00:00",
                            "Rusça":"00:00:00",
                        ],
                        "YDT Ders Soru" : [
                            "Almanca":"0",
                            "Arapça":"0",
                            "Fransızca":"0",
                            "İngilizce":"0",
                            "Rusça":"0",
                        ],
                        "TYT Türkçe Süre" : [
                            "Sözcükte Anlam":"00:00:00",
                            "Cümlede Anlam":"00:00:00",
                            "Paragraf":"00:00:00",
                            "Ses Bilgisi":"00:00:00",
                            "Yazım Kuralları":"00:00:00",
                            "Noktalama İşaretleri":"00:00:00",
                            "Sözcükte Yapı":"00:00:00",
                            "İsimler":"00:00:00",
                            "Sıfatlar":"00:00:00",
                            "Zamirler":"00:00:00",
                            "Zarflar":"00:00:00",
                            "Edat Bağlaç Ünlem":"00:00:00",
                            "Fiiller":"00:00:00",
                            "Fiilde Çatı":"00:00:00",
                            "Fiilimsiler":"00:00:00",
                            "Cümlenin Öğeleri":"00:00:00",
                            "Cümle Türleri":"00:00:00",
                            "Anlatım Bozuklukları":"00:00:00"
                        ],
                        "TYT Türkçe Soru" : [
                            "Sözcükte Anlam":"0",
                            "Cümlede Anlam":"0",
                            "Paragraf":"0",
                            "Ses Bilgisi":"0",
                            "Yazım Kuralları":"0",
                            "Noktalama İşaretleri":"0",
                            "Sözcükte Yapı":"0",
                            "İsimler":"0",
                            "Sıfatlar":"0",
                            "Zamirler":"0",
                            "Zarflar":"0",
                            "Edat Bağlaç Ünlem":"0",
                            "Fiiller":"0",
                            "Fiilde Çatı":"0",
                            "Fiilimsiler":"0",
                            "Cümlenin Öğeleri":"0",
                            "Cümle Türleri":"0",
                            "Anlatım Bozuklukları":"0"
                        ],
                        "TYT Türkçe Switch" : [
                            "Sözcükte Anlam":"0",
                            "Cümlede Anlam":"0",
                            "Paragraf":"0",
                            "Ses Bilgisi":"0",
                            "Yazım Kuralları":"0",
                            "Noktalama İşaretleri":"0",
                            "Sözcükte Yapı":"0",
                            "İsimler":"0",
                            "Sıfatlar":"0",
                            "Zamirler":"0",
                            "Zarflar":"0",
                            "Edat Bağlaç Ünlem":"0",
                            "Fiiller":"0",
                            "Fiilde Çatı":"0",
                            "Fiilimsiler":"0",
                            "Cümlenin Öğeleri":"0",
                            "Cümle Türleri":"0",
                            "Anlatım Bozuklukları":"0"
                        ],
                        "TYT Tarih Süre" : [
                            "Tarih Bilimine Giriş":"00:00:00",
                            "Uygarlığın Doğuşu ve İlk Uygarlıklar":"00:00:00",
                            "Eski Türk Tarihi":"00:00:00",
                            "İslam Tarihi":"00:00:00",
                            "Türk İslam Devletleri":"00:00:00",
                            "Türkiye Tarihi":"00:00:00",
                            "Beylikten Devlete":"00:00:00",
                            "Dünya Gücü Osmanlı Devleti":"00:00:00",
                            "Yeniçağ Avrupası":"00:00:00",
                            "Osmanlı Kültür ve Medeniyeti":"00:00:00",
                            "Arayış Yılları":"00:00:00",
                            "18. Yüzyılda Değişim ve Diplomasi":"00:00:00",
                            "Yakınçağ Avrupası":"00:00:00",
                            "En Uzun Yüzyıl":"00:00:00",
                            "20. Yüzyıl Başlarında Osmanlı Devleti":"00:00:00",
                            "1. Dünya Savaşı":"00:00:00",
                            "Milli Mücadeleye Hazırlık Dönemi":"00:00:00",
                            "Kurtuluş Savaşında Cepheler":"00:00:00",
                            "Türk İnkılabı":"00:00:00",
                            "Atatürkçülük ve Atatürk İlkeleri":"00:00:00",
                            "Türk Dış Politikası":"00:00:00"
                        ],
                        "TYT Tarih Soru" : [
                            "Tarih Bilimine Giriş":"0",
                            "Uygarlığın Doğuşu ve İlk Uygarlıklar":"0",
                            "Eski Türk Tarihi":"0",
                            "İslam Tarihi":"0",
                            "Türk İslam Devletleri":"0",
                            "Türkiye Tarihi":"0",
                            "Beylikten Devlete":"0",
                            "Dünya Gücü Osmanlı Devleti":"0",
                            "Yeniçağ Avrupası":"0",
                            "Osmanlı Kültür ve Medeniyeti":"0",
                            "Arayış Yılları":"0",
                            "18. Yüzyılda Değişim ve Diplomasi":"0",
                            "Yakınçağ Avrupası":"0",
                            "En Uzun Yüzyıl":"0",
                            "20. Yüzyıl Başlarında Osmanlı Devleti":"0",
                            "1. Dünya Savaşı":"0",
                            "Milli Mücadeleye Hazırlık Dönemi":"0",
                            "Kurtuluş Savaşında Cepheler":"0",
                            "Türk İnkılabı":"0",
                            "Atatürkçülük ve Atatürk İlkeleri":"0",
                            "Türk Dış Politikası":"0"
                        ],
                        "TYT Tarih Switch" : [
                            "Tarih Bilimine Giriş":"0",
                            "Uygarlığın Doğuşu ve İlk Uygarlıklar":"0",
                            "Eski Türk Tarihi":"0",
                            "İslam Tarihi":"0",
                            "Türk İslam Devletleri":"0",
                            "Türkiye Tarihi":"0",
                            "Beylikten Devlete":"0",
                            "Dünya Gücü Osmanlı Devleti":"0",
                            "Yeniçağ Avrupası":"0",
                            "Osmanlı Kültür ve Medeniyeti":"0",
                            "Arayış Yılları":"0",
                            "18. Yüzyılda Değişim ve Diplomasi":"0",
                            "Yakınçağ Avrupası":"0",
                            "En Uzun Yüzyıl":"0",
                            "20. Yüzyıl Başlarında Osmanlı Devleti":"0",
                            "1. Dünya Savaşı":"0",
                            "Milli Mücadeleye Hazırlık Dönemi":"0",
                            "Kurtuluş Savaşında Cepheler":"0",
                            "Türk İnkılabı":"0",
                            "Atatürkçülük ve Atatürk İlkeleri":"0",
                            "Türk Dış Politikası":"0"
                        ],
                        "TYT Coğrafya Süre" : [
                            "Harita Bilgisi":"00:00:00",
                            "Dünyanın Şekli ve Hareketleri":"00:00:00",
                            "İklim Bilgisi":"00:00:00",
                            "Türkiye’nin İklimi ve Yer Şekilleri":"00:00:00",
                            "Yer’in Şekillenmesi":"00:00:00",
                            "İç ve Dış Kuvvetler":"00:00:00",
                            "Toprak Tipleri":"00:00:00",
                            "Nüfus":"00:00:00",
                            "Ortak Payda: Bölge":"00:00:00",
                            "Ulaşım Yolları":"00:00:00",
                            "Çevre ve İnsan":"00:00:00",
                            "Doğal Afetler":"00:00:00"
                        ],
                        "TYT Coğrafya Soru" : [
                            "Harita Bilgisi":"0",
                            "Dünyanın Şekli ve Hareketleri":"0",
                            "İklim Bilgisi":"0",
                            "Türkiye’nin İklimi ve Yer Şekilleri":"0",
                            "Yer’in Şekillenmesi":"0",
                            "İç ve Dış Kuvvetler":"0",
                            "Toprak Tipleri":"0",
                            "Nüfus":"0",
                            "Ortak Payda: Bölge":"0",
                            "Ulaşım Yolları":"0",
                            "Çevre ve İnsan":"0",
                            "Doğal Afetler":"0"
                        ],
                        "TYT Coğrafya Switch" : [
                            "Harita Bilgisi":"0",
                            "Dünyanın Şekli ve Hareketleri":"0",
                            "İklim Bilgisi":"0",
                            "Türkiye’nin İklimi ve Yer Şekilleri":"0",
                            "Yer’in Şekillenmesi":"0",
                            "İç ve Dış Kuvvetler":"0",
                            "Toprak Tipleri":"0",
                            "Nüfus":"0",
                            "Ortak Payda: Bölge":"0",
                            "Ulaşım Yolları":"0",
                            "Çevre ve İnsan":"0",
                            "Doğal Afetler":"0"
                        ],
                        "TYT Felsefe Süre" : [
                            "Felsefenin Alanı":"00:00:00",
                            "Bilgi Felsefesi":"00:00:00",
                            "Bilim Felsefesi":"00:00:00",
                            "Varlık Felsefesi":"00:00:00",
                            "Ahlak Felsefesi":"00:00:00",
                            "Siyaset Felsefesi":"00:00:00",
                            "Sanat Felsefesi":"00:00:00",
                            "Din Felsefesi":"00:00:00"
                        ],
                        "TYT Felsefe Soru" : [
                            "Felsefenin Alanı":"0",
                            "Bilgi Felsefesi":"0",
                            "Bilim Felsefesi":"0",
                            "Varlık Felsefesi":"0",
                            "Ahlak Felsefesi":"0",
                            "Siyaset Felsefesi":"0",
                            "Sanat Felsefesi":"0",
                            "Din Felsefesi":"0"
                        ],
                        "TYT Felsefe Switch" : [
                            "Felsefenin Alanı":"0",
                            "Bilgi Felsefesi":"0",
                            "Bilim Felsefesi":"0",
                            "Varlık Felsefesi":"0",
                            "Ahlak Felsefesi":"0",
                            "Siyaset Felsefesi":"0",
                            "Sanat Felsefesi":"0",
                            "Din Felsefesi":"0"
                        ],
                        "TYT Din Kültürü Süre" : [
                            "Kuran ve Yorumu":"00:00:00",
                            "Hz. Muhammed’in Hayatı":"00:00:00",
                            "İslam Düşüncesinde Yorumlar":"00:00:00",
                            "İslam Dinine Göre Kötü Alışkanlıklar":"00:00:00",
                            "Hazreti Muhammed":"00:00:00",
                            "İslam Düşüncesinde Tasavvuf":"00:00:00",
                            "Vahiy ve Akıl Kur’an Yorumları":"00:00:00",
                        ],
                        "TYT Din Kültürü Soru" : [
                            "Kuran ve Yorumu":"0",
                            "Hz. Muhammed’in Hayatı":"0",
                            "İslam Düşüncesinde Yorumlar":"0",
                            "İslam Dinine Göre Kötü Alışkanlıklar":"0",
                            "Hazreti Muhammed":"0",
                            "İslam Düşüncesinde Tasavvuf":"0",
                            "Vahiy ve Akıl Kur’an Yorumları":"0",
                        ],
                        "TYT Din Kültürü Switch" : [
                            "Kuran ve Yorumu":"0",
                            "Hz. Muhammed’in Hayatı":"0",
                            "İslam Düşüncesinde Yorumlar":"0",
                            "İslam Dinine Göre Kötü Alışkanlıklar":"0",
                            "Hazreti Muhammed":"0",
                            "İslam Düşüncesinde Tasavvuf":"0",
                            "Vahiy ve Akıl Kur’an Yorumları":"0",
                        ],
                        "TYT Matematik Süre" : [
                            "Temel Kavramlar":"00:00:00",
                            "Sayı Basamakları":"00:00:00",
                            "Rasyonel Sayılar":"00:00:00",
                            "Ondalıklı Sayılar":"00:00:00",
                            "Basit Eşitsizlikler":"00:00:00",
                            "Mutlak Değer":"00:00:00",
                            "Üslü Sayılar":"00:00:00",
                            "Köklü Sayılar":"00:00:00",
                            "Çarpanlara Ayırma":"00:00:00",
                            "Denklem Çözme":"00:00:00",
                            "Oran Orantı":"00:00:00",
                            "Problemler":"00:00:00",
                            "Kümeler":"00:00:00",
                            "Fonksiyonlar":"00:00:00",
                            "Permütasyon":"00:00:00",
                            "Kombinasyon":"00:00:00",
                            "Binom":"00:00:00",
                            "Olasılık":"00:00:00",
                            "İstatistik":"00:00:00",
                            "Polinomlar":"00:00:00",
                            "2. Dereceden Denklemler":"00:00:00",
                            "Karmaşık Sayılar":"00:00:00",
                            "Parabol":"00:00:00"
                        ],
                        "TYT Matematik Soru" : [
                            "Temel Kavramlar":"0",
                            "Sayı Basamakları":"0",
                            "Rasyonel Sayılar":"0",
                            "Ondalıklı Sayılar":"0",
                            "Basit Eşitsizlikler":"0",
                            "Mutlak Değer":"0",
                            "Üslü Sayılar":"0",
                            "Köklü Sayılar":"0",
                            "Çarpanlara Ayırma":"0",
                            "Denklem Çözme":"0",
                            "Oran Orantı":"0",
                            "Problemler":"0",
                            "Kümeler":"0",
                            "Fonksiyonlar":"0",
                            "Permütasyon":"0",
                            "Kombinasyon":"0",
                            "Binom":"0",
                            "Olasılık":"0",
                            "İstatistik":"0",
                            "Polinomlar":"0",
                            "2. Dereceden Denklemler":"0",
                            "Karmaşık Sayılar":"0",
                            "Parabol":"0"
                        ],
                        "TYT Matematik Switch" : [
                            "Temel Kavramlar":"0",
                            "Sayı Basamakları":"0",
                            "Rasyonel Sayılar":"0",
                            "Ondalıklı Sayılar":"0",
                            "Basit Eşitsizlikler":"0",
                            "Mutlak Değer":"0",
                            "Üslü Sayılar":"0",
                            "Köklü Sayılar":"0",
                            "Çarpanlara Ayırma":"0",
                            "Denklem Çözme":"0",
                            "Oran Orantı":"0",
                            "Problemler":"0",
                            "Kümeler":"0",
                            "Fonksiyonlar":"0",
                            "Permütasyon":"0",
                            "Kombinasyon":"0",
                            "Binom":"0",
                            "Olasılık":"0",
                            "İstatistik":"0",
                            "Polinomlar":"0",
                            "2. Dereceden Denklemler":"0",
                            "Karmaşık Sayılar":"0",
                            "Parabol":"0"
                        ],
                        "TYT Geometri Süre" : [
                            "Temel Kavramlar":"00:00:00",
                            "Doğruda Açılar":"00:00:00",
                            "Üçgende Açılar":"00:00:00",
                            "Dik Üçgen":"00:00:00",
                            "İkizkenar Üçgen":"00:00:00",
                            "Eşkenar Üçgen":"00:00:00",
                            "Açıortay":"00:00:00",
                            "Kenarortay":"00:00:00",
                            "Üçgende Alan":"00:00:00",
                            "Üçgende Benzerlik":"00:00:00",
                            "Açı Kenar Bağıntıları":"00:00:00",
                            "Çokgenler":"00:00:00",
                            "Dörtgenler":"00:00:00",
                            "Deltoid":"00:00:00",
                            "Paralelkenar":"00:00:00",
                            "Eşkenar Dörtgen":"00:00:00",
                            "Dikdörtgen":"00:00:00",
                            "Kare":"00:00:00",
                            "İkizkenar":"00:00:00",
                            "Yamuk":"00:00:00",
                            "Çember ve Daire":"00:00:00",
                            "Noktanın Analitiği":"00:00:00",
                            "Doğrunun Analitiği":"00:00:00",
                            "Dikdörtgenler Prizması":"00:00:00",
                            "Küp":"00:00:00",
                            "Silindir":"00:00:00",
                            "Piramit":"00:00:00",
                            "Koni":"00:00:00",
                            "Küre":"00:00:00"
                        ],
                        "TYT Geometri Soru" : [
                            "Temel Kavramlar":"0",
                            "Doğruda Açılar":"0",
                            "Üçgende Açılar":"0",
                            "Dik Üçgen":"0",
                            "İkizkenar Üçgen":"0",
                            "Eşkenar Üçgen":"0",
                            "Açıortay":"0",
                            "Kenarortay":"0",
                            "Üçgende Alan":"0",
                            "Üçgende Benzerlik":"0",
                            "Açı Kenar Bağıntıları":"0",
                            "Çokgenler":"0",
                            "Dörtgenler":"0",
                            "Deltoid":"0",
                            "Paralelkenar":"0",
                            "Eşkenar Dörtgen":"0",
                            "Dikdörtgen":"0",
                            "Kare":"0",
                            "İkizkenar":"0",
                            "Yamuk":"0",
                            "Çember ve Daire":"0",
                            "Noktanın Analitiği":"0",
                            "Doğrunun Analitiği":"0",
                            "Dikdörtgenler Prizması":"0",
                            "Küp":"0",
                            "Silindir":"0",
                            "Piramit":"0",
                            "Koni":"0",
                            "Küre":"0"
                        ],
                        "TYT Geometri Switch" : [
                            "Temel Kavramlar":"0",
                            "Doğruda Açılar":"0",
                            "Üçgende Açılar":"0",
                            "Dik Üçgen":"0",
                            "İkizkenar Üçgen":"0",
                            "Eşkenar Üçgen":"0",
                            "Açıortay":"0",
                            "Kenarortay":"0",
                            "Üçgende Alan":"0",
                            "Üçgende Benzerlik":"0",
                            "Açı Kenar Bağıntıları":"0",
                            "Çokgenler":"0",
                            "Dörtgenler":"0",
                            "Deltoid":"0",
                            "Paralelkenar":"0",
                            "Eşkenar Dörtgen":"0",
                            "Dikdörtgen":"0",
                            "Kare":"0",
                            "İkizkenar":"0",
                            "Yamuk":"0",
                            "Çember ve Daire":"0",
                            "Noktanın Analitiği":"0",
                            "Doğrunun Analitiği":"0",
                            "Dikdörtgenler Prizması":"0",
                            "Küp":"0",
                            "Silindir":"0",
                            "Piramit":"0",
                            "Koni":"0",
                            "Küre":"0"
                        ],
                        "TYT Fizik Süre" : [
                            "Fizik Bilimine Giriş":"00:00:00",
                            "Madde ve Özellikleri":"00:00:00",
                            "Sıvıların Kaldırma Kuvveti":"00:00:00",
                            "Basınç":"00:00:00",
                            "Isı, Sıcaklık ve Genleşme":"00:00:00",
                            "Hareket":"00:00:00",
                            "Dinamik":"00:00:00",
                            "İş, Güç ve Enerji":"00:00:00",
                            "Elektrik":"00:00:00",
                            "Optik":"00:00:00",
                            "Manyetizma":"00:00:00",
                            "Dalgalar":"00:00:00"
                        ],
                        "TYT Fizik Soru" : [
                            "Fizik Bilimine Giriş":"0",
                            "Madde ve Özellikleri":"0",
                            "Sıvıların Kaldırma Kuvveti":"0",
                            "Basınç":"0",
                            "Isı, Sıcaklık ve Genleşme":"0",
                            "Hareket":"0",
                            "Dinamik":"0",
                            "İş, Güç ve Enerji":"0",
                            "Elektrik":"0",
                            "Optik":"0",
                            "Manyetizma":"0",
                            "Dalgalar":"0"
                        ],
                        "TYT Fizik Switch" : [
                            "Fizik Bilimine Giriş":"0",
                            "Madde ve Özellikleri":"0",
                            "Sıvıların Kaldırma Kuvveti":"0",
                            "Basınç":"0",
                            "Isı, Sıcaklık ve Genleşme":"0",
                            "Hareket":"0",
                            "Dinamik":"0",
                            "İş, Güç ve Enerji":"0",
                            "Elektrik":"0",
                            "Optik":"0",
                            "Manyetizma":"0",
                            "Dalgalar":"0"
                        ],
                        "TYT Kimya Süre" : [
                            "Kimya Bilimi":"00:00:00",
                            "Atom ve Periyodik Sistem":"00:00:00",
                            "Kimyasal Türler Arası Etkileşimler":"00:00:00",
                            "Kimyasal Hesaplamalar":"00:00:00",
                            "Kimyanın Temel Kanunları":"00:00:00",
                            "Asit, Baz ve Tuz":"00:00:00",
                            "Maddenin Halleri":"00:00:00",
                            "Karışımlar":"00:00:00",
                            "Doğa ve Kimya":"00:00:00",
                            "Kimya Her Yerde":"00:00:00"
                        ],
                        "TYT Kimya Soru" : [
                            "Kimya Bilimi":"0",
                            "Atom ve Periyodik Sistem":"0",
                            "Kimyasal Türler Arası Etkileşimler":"0",
                            "Kimyasal Hesaplamalar":"0",
                            "Kimyanın Temel Kanunları":"0",
                            "Asit, Baz ve Tuz":"0",
                            "Maddenin Halleri":"0",
                            "Karışımlar":"0",
                            "Doğa ve Kimya":"0",
                            "Kimya Her Yerde":"0"
                        ],
                        "TYT Kimya Switch" : [
                            "Kimya Bilimi":"0",
                            "Atom ve Periyodik Sistem":"0",
                            "Kimyasal Türler Arası Etkileşimler":"0",
                            "Kimyasal Hesaplamalar":"0",
                            "Kimyanın Temel Kanunları":"0",
                            "Asit, Baz ve Tuz":"0",
                            "Maddenin Halleri":"0",
                            "Karışımlar":"0",
                            "Doğa ve Kimya":"0",
                            "Kimya Her Yerde":"0"
                        ],
                        "TYT Biyoloji Süre" : [
                            "Canlıların Ortak Özellikleri":"00:00:00",
                            "Canlıların Temel Bileşenleri":"00:00:00",
                            "Hücre ve Organelleri":"00:00:00",
                            "Hücre Zarından Madde Geçişi":"00:00:00",
                            "Canlıların Sınıflandırılması":"00:00:00",
                            "Mitoz ve Eşeysiz Üreme":"00:00:00",
                            "Mayoz ve Eşeyli Üreme":"00:00:00",
                            "Kalıtım":"00:00:00",
                            "Ekosistem Ekolojisi":"00:00:00",
                            "Güncel Çevre Sorunları":"00:00:00"
                        ],
                        "TYT Biyoloji Soru" : [
                            "Canlıların Ortak Özellikleri":"0",
                            "Canlıların Temel Bileşenleri":"0",
                            "Hücre ve Organelleri":"0",
                            "Hücre Zarından Madde Geçişi":"0",
                            "Canlıların Sınıflandırılması":"0",
                            "Mitoz ve Eşeysiz Üreme":"0",
                            "Mayoz ve Eşeyli Üreme":"0",
                            "Kalıtım":"0",
                            "Ekosistem Ekolojisi":"0",
                            "Güncel Çevre Sorunları":"0"
                        ],
                        "TYT Biyoloji Switch" : [
                            "Canlıların Ortak Özellikleri":"0",
                            "Canlıların Temel Bileşenleri":"0",
                            "Hücre ve Organelleri":"0",
                            "Hücre Zarından Madde Geçişi":"0",
                            "Canlıların Sınıflandırılması":"0",
                            "Mitoz ve Eşeysiz Üreme":"0",
                            "Mayoz ve Eşeyli Üreme":"0",
                            "Kalıtım":"0",
                            "Ekosistem Ekolojisi":"0",
                            "Güncel Çevre Sorunları":"0"
                        ],
                        "AYT Edebiyat Süre" : [
                            "Anlam Bilgisi":"00:00:00",
                            "Dil Bilgisi":"00:00:00",
                            "Güzel Sanatlar ve Edebiyat":"00:00:00",
                            "Metinlerin Sınıflandırılması":"00:00:00",
                            "Şiir Bilgisi":"00:00:00",
                            "Edebi Sanatlar":"00:00:00",
                            "Türk Edebiyatı Dönemleri":"00:00:00",
                            "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi":"00:00:00",
                            "Halk Edebiyatı":"00:00:00",
                            "Divan Edebiyatı":"00:00:00",
                            "Tanzimat Edebiyatı":"00:00:00",
                            "Servet-i Fünun Edebiyatı":"00:00:00",
                            "Fecr-i Ati Edebiyatı":"00:00:00",
                            "Milli Edebiyat":"00:00:00",
                            "Cumhuriyet Şiiri":"00:00:00",
                            "Cumhuriyet Romanı":"00:00:00",
                            "Cumhuriyet Dönemi":"00:00:00",
                            "Edebiyat Akımları":"00:00:00",
                            "Dünya Edebiyatı":"00:00:00"
                        ],
                        "AYT Edebiyat Soru" : [
                            "Anlam Bilgisi":"0",
                            "Dil Bilgisi":"0",
                            "Güzel Sanatlar ve Edebiyat":"0",
                            "Metinlerin Sınıflandırılması":"0",
                            "Şiir Bilgisi":"0",
                            "Edebi Sanatlar":"0",
                            "Türk Edebiyatı Dönemleri":"0",
                            "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi":"0",
                            "Halk Edebiyatı":"0",
                            "Divan Edebiyatı":"0",
                            "Tanzimat Edebiyatı":"0",
                            "Servet-i Fünun Edebiyatı":"0",
                            "Fecr-i Ati Edebiyatı":"0",
                            "Milli Edebiyat":"0",
                            "Cumhuriyet Şiiri":"0",
                            "Cumhuriyet Romanı":"0",
                            "Cumhuriyet Dönemi":"0",
                            "Edebiyat Akımları":"0",
                            "Dünya Edebiyatı":"0"
                        ],
                        "AYT Edebiyat Switch" : [
                            "Anlam Bilgisi":"0",
                            "Dil Bilgisi":"0",
                            "Güzel Sanatlar ve Edebiyat":"0",
                            "Metinlerin Sınıflandırılması":"0",
                            "Şiir Bilgisi":"0",
                            "Edebi Sanatlar":"0",
                            "Türk Edebiyatı Dönemleri":"0",
                            "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi":"0",
                            "Halk Edebiyatı":"0",
                            "Divan Edebiyatı":"0",
                            "Tanzimat Edebiyatı":"0",
                            "Servet-i Fünun Edebiyatı":"0",
                            "Fecr-i Ati Edebiyatı":"0",
                            "Milli Edebiyat":"0",
                            "Cumhuriyet Şiiri":"0",
                            "Cumhuriyet Romanı":"0",
                            "Cumhuriyet Dönemi":"0",
                            "Edebiyat Akımları":"0",
                            "Dünya Edebiyatı":"0"
                        ],
                        "AYT Tarih Süre" : [
                            "Tarih Bilimi":"00:00:00",
                            "İlk Uygarlıklar":"00:00:00",
                            "İlk Türk Devletleri":"00:00:00",
                            "İslam Tarihi ve Uygarlığı":"00:00:00",
                            "Türk İslam Devletleri":"00:00:00",
                            "Orta Çağ ve Avrupa Tarihi":"00:00:00",
                            "Türkiye Tarihi":"00:00:00",
                            "Beylikten Devlete":"00:00:00",
                            "Dünya Gücü: Osmanlı Devleti":"00:00:00",
                            "Osmanlı Kültür ve Medeniyeti":"00:00:00",
                            "Yeni ve Yakın Çağda Avrupa Tarihi":"00:00:00",
                            "Arayış Yılları":"00:00:00",
                            "Yeni Çağda Avrupa":"00:00:00",
                            "En Uzun Yüzyıl":"00:00:00",
                            "20. Yüzyıl Başlarında Osmanlı Devleti":"00:00:00",
                            "1. Dünya Savaşı Milli Mücadeleye Hazırlık Dönemi":"00:00:00",
                            "Kurtuluş Savaşı ve Antlaşmalar":"00:00:00",
                            "I. TBMM Dönemi":"00:00:00",
                            "Türk İnkılabı":"00:00:00",
                            "Atatürkçülük ve Atatürk İlkeleri":"00:00:00",
                            "Türk Dış Politikası":"00:00:00",
                            "Atatürk’ün Ölümü":"00:00:00",
                            "20. Yüzyıl Başlarında Dünya":"00:00:00",
                            "İkinci Dünya Savaşı":"00:00:00",
                            "Soğuk Savaş Dönemi":"00:00:00",
                            "Yumuşama Dönemi ve Sonrası":"00:00:00",
                            "Küreselleşen Dünya":"00:00:00",
                            "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya":"00:00:00"
                        ],
                        "AYT Tarih Soru" : [
                            "Tarih Bilimi":"0",
                            "İlk Uygarlıklar":"0",
                            "İlk Türk Devletleri":"0",
                            "İslam Tarihi ve Uygarlığı":"0",
                            "Türk İslam Devletleri":"0",
                            "Orta Çağ ve Avrupa Tarihi":"0",
                            "Türkiye Tarihi":"0",
                            "Beylikten Devlete":"0",
                            "Dünya Gücü: Osmanlı Devleti":"0",
                            "Osmanlı Kültür ve Medeniyeti":"0",
                            "Yeni ve Yakın Çağda Avrupa Tarihi":"0",
                            "Arayış Yılları":"0",
                            "Yeni Çağda Avrupa":"0",
                            "En Uzun Yüzyıl":"0",
                            "20. Yüzyıl Başlarında Osmanlı Devleti":"0",
                            "1. Dünya Savaşı Milli Mücadeleye Hazırlık Dönemi":"0",
                            "Kurtuluş Savaşı ve Antlaşmalar":"0",
                            "I. TBMM Dönemi":"0",
                            "Türk İnkılabı":"0",
                            "Atatürkçülük ve Atatürk İlkeleri":"0",
                            "Türk Dış Politikası":"0",
                            "Atatürk’ün Ölümü":"0",
                            "20. Yüzyıl Başlarında Dünya":"0",
                            "İkinci Dünya Savaşı":"0",
                            "Soğuk Savaş Dönemi":"0",
                            "Yumuşama Dönemi ve Sonrası":"0",
                            "Küreselleşen Dünya":"0",
                            "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya":"0"
                        ],
                        "AYT Tarih Switch" : [
                            "Tarih Bilimi":"0",
                            "İlk Uygarlıklar":"0",
                            "İlk Türk Devletleri":"0",
                            "İslam Tarihi ve Uygarlığı":"0",
                            "Türk İslam Devletleri":"0",
                            "Orta Çağ ve Avrupa Tarihi":"0",
                            "Türkiye Tarihi":"0",
                            "Beylikten Devlete":"0",
                            "Dünya Gücü: Osmanlı Devleti":"0",
                            "Osmanlı Kültür ve Medeniyeti":"0",
                            "Yeni ve Yakın Çağda Avrupa Tarihi":"0",
                            "Arayış Yılları":"0",
                            "Yeni Çağda Avrupa":"0",
                            "En Uzun Yüzyıl":"0",
                            "20. Yüzyıl Başlarında Osmanlı Devleti":"0",
                            "1. Dünya Savaşı Milli Mücadeleye Hazırlık Dönemi":"0",
                            "Kurtuluş Savaşı ve Antlaşmalar":"0",
                            "I. TBMM Dönemi":"0",
                            "Türk İnkılabı":"0",
                            "Atatürkçülük ve Atatürk İlkeleri":"0",
                            "Türk Dış Politikası":"0",
                            "Atatürk’ün Ölümü":"0",
                            "20. Yüzyıl Başlarında Dünya":"0",
                            "İkinci Dünya Savaşı":"0",
                            "Soğuk Savaş Dönemi":"0",
                            "Yumuşama Dönemi ve Sonrası":"0",
                            "Küreselleşen Dünya":"0",
                            "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya":"0"
                        ],
                        "AYT Coğrafya Süre" : [
                            "Ekosistem":"00:00:00",
                            "Doğadaki Ekstrem Olaylar":"00:00:00",
                            "İlk Medeniyet ve Şehirler":"00:00:00",
                            "Nüfus Politikaları":"00:00:00",
                            "Türkiye’de Nüfus ve Yerleşme":"00:00:00",
                            "Ekonomik Faaliyetler":"00:00:00",
                            "Göç ve Şehirleşme":"00:00:00",
                            "Türkiye Ekonomisi":"00:00:00",
                            "Türkiye’nin Jeopolitik Konumu":"00:00:00",
                            "Bölgesel Kalkınma Projeleri":"00:00:00",
                            "İklim ve Yer şekilleri":"00:00:00",
                            "Ülkeler Arası Etkileşim":"00:00:00",
                            "Küresel ve Bölgesel Örgütler":"00:00:00",
                            "Üretim Alanları ve Ulaşım Ağları":"00:00:00",
                            "Bölgeler ve Ülkeler":"00:00:00",
                            "Çevre ve Toplum":"00:00:00",
                            "Doğal Afetler":"00:00:00"
                        ],
                        "AYT Coğrafya Soru" : [
                            "Ekosistem":"0",
                            "Doğadaki Ekstrem Olaylar":"0",
                            "İlk Medeniyet ve Şehirler":"0",
                            "Nüfus Politikaları":"0",
                            "Türkiye’de Nüfus ve Yerleşme":"0",
                            "Ekonomik Faaliyetler":"0",
                            "Göç ve Şehirleşme":"0",
                            "Türkiye Ekonomisi":"0",
                            "Türkiye’nin Jeopolitik Konumu":"0",
                            "Bölgesel Kalkınma Projeleri":"0",
                            "İklim ve Yer şekilleri":"0",
                            "Ülkeler Arası Etkileşim":"0",
                            "Küresel ve Bölgesel Örgütler":"0",
                            "Üretim Alanları ve Ulaşım Ağları":"0",
                            "Bölgeler ve Ülkeler":"0",
                            "Çevre ve Toplum":"0",
                            "Doğal Afetler":"0"
                        ],
                        "AYT Coğrafya Switch" : [
                            "Ekosistem":"0",
                            "Doğadaki Ekstrem Olaylar":"0",
                            "İlk Medeniyet ve Şehirler":"0",
                            "Nüfus Politikaları":"0",
                            "Türkiye’de Nüfus ve Yerleşme":"0",
                            "Ekonomik Faaliyetler":"0",
                            "Göç ve Şehirleşme":"0",
                            "Türkiye Ekonomisi":"0",
                            "Türkiye’nin Jeopolitik Konumu":"0",
                            "Bölgesel Kalkınma Projeleri":"0",
                            "İklim ve Yer şekilleri":"0",
                            "Ülkeler Arası Etkileşim":"0",
                            "Küresel ve Bölgesel Örgütler":"0",
                            "Üretim Alanları ve Ulaşım Ağları":"0",
                            "Bölgeler ve Ülkeler":"0",
                            "Çevre ve Toplum":"0",
                            "Doğal Afetler":"0"
                        ],
                        "AYT Felsefe Süre" : [
                            "Felsefe’nin Konusu":"00:00:00",
                            "Bilgi Felsefesi":"00:00:00",
                            "Varlık Felsefesi":"00:00:00",
                            "Ahlak Felsefesi":"00:00:00",
                            "Sanat Felsefesi":"00:00:00",
                            "Din Felsefesi":"00:00:00",
                            "Siyaset Felsefesi":"00:00:00",
                            "Bilim Felsefesi":"00:00:00",
                            "Mantığa Giriş":"00:00:00",
                            "Klasik Mantık":"00:00:00",
                            "Mantık ve Dil":"00:00:00",
                            "Sembolik Mantık":"00:00:00",
                            "Psikoloji Bilimini Tanıyalım":"00:00:00",
                            "Psikolojinin Temel Süreçleri":"00:00:00",
                            "Öğrenme Bellek Düşünme":"00:00:00",
                            "Ruh Sağlığının Temelleri":"00:00:00",
                            "Sosyolojiye Giriş":"00:00:00",
                            "Birey ve Toplum":"00:00:00",
                            "Toplumsal Yapı":"00:00:00",
                            "Toplumsal Değişme ve Gelişme":"00:00:00",
                            "Toplum ve Kültür":"00:00:00",
                            "Toplumsal Kurumlar":"00:00:00"
                        ],
                        "AYT Felsefe Soru" : [
                            "Felsefe’nin Konusu":"0",
                            "Bilgi Felsefesi":"0",
                            "Varlık Felsefesi":"0",
                            "Ahlak Felsefesi":"0",
                            "Sanat Felsefesi":"0",
                            "Din Felsefesi":"0",
                            "Siyaset Felsefesi":"0",
                            "Bilim Felsefesi":"0",
                            "Mantığa Giriş":"0",
                            "Klasik Mantık":"0",
                            "Mantık ve Dil":"0",
                            "Sembolik Mantık":"0",
                            "Psikoloji Bilimini Tanıyalım":"0",
                            "Psikolojinin Temel Süreçleri":"0",
                            "Öğrenme Bellek Düşünme":"0",
                            "Ruh Sağlığının Temelleri":"0",
                            "Sosyolojiye Giriş":"0",
                            "Birey ve Toplum":"0",
                            "Toplumsal Yapı":"0",
                            "Toplumsal Değişme ve Gelişme":"0",
                            "Toplum ve Kültür":"0",
                            "Toplumsal Kurumlar":"0"
                        ],
                        "AYT Felsefe Switch" : [
                            "Felsefe’nin Konusu":"0",
                            "Bilgi Felsefesi":"0",
                            "Varlık Felsefesi":"0",
                            "Ahlak Felsefesi":"0",
                            "Sanat Felsefesi":"0",
                            "Din Felsefesi":"0",
                            "Siyaset Felsefesi":"0",
                            "Bilim Felsefesi":"0",
                            "Mantığa Giriş":"0",
                            "Klasik Mantık":"0",
                            "Mantık ve Dil":"0",
                            "Sembolik Mantık":"0",
                            "Psikoloji Bilimini Tanıyalım":"0",
                            "Psikolojinin Temel Süreçleri":"0",
                            "Öğrenme Bellek Düşünme":"0",
                            "Ruh Sağlığının Temelleri":"0",
                            "Sosyolojiye Giriş":"0",
                            "Birey ve Toplum":"0",
                            "Toplumsal Yapı":"0",
                            "Toplumsal Değişme ve Gelişme":"0",
                            "Toplum ve Kültür":"0",
                            "Toplumsal Kurumlar":"0"
                        ],
                        "AYT Din Kültürü Süre" : [
                            "Dünya ve Ahiret":"00:00:00",
                            "Kur’an’a Göre Hz. Muhammed":"00:00:00",
                            "Kur’an’da Bazı Kavramlar":"00:00:00",
                            "Kur’an’dan Mesajlar":"00:00:00",
                            "İnançla İlgili Meseleler":"00:00:00",
                            "İslam ve Bilim":"00:00:00",
                            "Anadolu’da İslam":"00:00:00",
                            "İslam Düşüncesinde Tasavvufi Yorumlar ve Mezhepler":"00:00:00",
                            "Güncel Dini Meseleler":"00:00:00",
                            "Yaşayan Dinler":"00:00:00"
                        ],
                        "AYT Din Kültürü Soru" : [
                            "Dünya ve Ahiret":"0",
                            "Kur’an’a Göre Hz. Muhammed":"0",
                            "Kur’an’da Bazı Kavramlar":"0",
                            "Kur’an’dan Mesajlar":"0",
                            "İnançla İlgili Meseleler":"0",
                            "İslam ve Bilim":"0",
                            "Anadolu’da İslam":"0",
                            "İslam Düşüncesinde Tasavvufi Yorumlar ve Mezhepler":"0",
                            "Güncel Dini Meseleler":"0",
                            "Yaşayan Dinler":"0"
                        ],
                        "AYT Din Kültürü Switch" : [
                            "Dünya ve Ahiret":"0",
                            "Kur’an’a Göre Hz. Muhammed":"0",
                            "Kur’an’da Bazı Kavramlar":"0",
                            "Kur’an’dan Mesajlar":"0",
                            "İnançla İlgili Meseleler":"0",
                            "İslam ve Bilim":"0",
                            "Anadolu’da İslam":"0",
                            "İslam Düşüncesinde Tasavvufi Yorumlar ve Mezhepler":"0",
                            "Güncel Dini Meseleler":"0",
                            "Yaşayan Dinler":"0"
                        ],
                        "AYT Matematik Süre" : [
                            "Temel Kavramlar":"00:00:00",
                            "Sayı Basamakları":"00:00:00",
                            "Bölme ve Bölünebilme":"00:00:00",
                            "EBOB ve EKOK":"00:00:00",
                            "Rasyonel Sayılar":"00:00:00",
                            "Basit Eşitsizlikler":"00:00:00",
                            "Mutlak Değer":"00:00:00",
                            "Üslü Sayılar":"00:00:00",
                            "Köklü Sayılar":"00:00:00",
                            "Çarpanlara Ayırma":"00:00:00",
                            "Oran Orantı":"00:00:00",
                            "Denklem Çözme":"00:00:00",
                            "Problemler":"00:00:00",
                            "Kümeler":"00:00:00",
                            "Kartezyen Çarpım":"00:00:00",
                            "Mantık":"00:00:00",
                            "Fonskiyonlar":"00:00:00",
                            "Polinomlar":"00:00:00",
                            "2. Dereceden Denklemler":"00:00:00",
                            "Permütasyon ve Kombinasyon":"00:00:00",
                            "Binom ve Olasılık":"00:00:00",
                            "İstatistik":"00:00:00",
                            "Karmaşık Sayılar":"00:00:00",
                            "2. Dereceden Eşitsizlikler":"00:00:00",
                            "Parabol":"00:00:00",
                            "Trigonometri":"00:00:00",
                            "Logaritma":"00:00:00",
                            "Diziler":"00:00:00",
                            "Limit":"00:00:00",
                            "Türev":"00:00:00",
                            "İntegral":"00:00:00"
                        ],
                        "AYT Matematik Soru" : [
                            "Temel Kavramlar":"0",
                            "Sayı Basamakları":"0",
                            "Bölme ve Bölünebilme":"0",
                            "EBOB ve EKOK":"0",
                            "Rasyonel Sayılar":"0",
                            "Basit Eşitsizlikler":"0",
                            "Mutlak Değer":"0",
                            "Üslü Sayılar":"0",
                            "Köklü Sayılar":"0",
                            "Çarpanlara Ayırma":"0",
                            "Oran Orantı":"0",
                            "Denklem Çözme":"0",
                            "Problemler":"0",
                            "Kümeler":"0",
                            "Kartezyen Çarpım":"0",
                            "Mantık":"0",
                            "Fonskiyonlar":"0",
                            "Polinomlar":"0",
                            "2. Dereceden Denklemler":"0",
                            "Permütasyon ve Kombinasyon":"0",
                            "Binom ve Olasılık":"0",
                            "İstatistik":"0",
                            "Karmaşık Sayılar":"0",
                            "2. Dereceden Eşitsizlikler":"0",
                            "Parabol":"0",
                            "Trigonometri":"0",
                            "Logaritma":"0",
                            "Diziler":"0",
                            "Limit":"0",
                            "Türev":"0",
                            "İntegral":"0"
                        ],
                        "AYT Matematik Switch" : [
                            "Temel Kavramlar":"0",
                            "Sayı Basamakları":"0",
                            "Bölme ve Bölünebilme":"0",
                            "EBOB ve EKOK":"0",
                            "Rasyonel Sayılar":"0",
                            "Basit Eşitsizlikler":"0",
                            "Mutlak Değer":"0",
                            "Üslü Sayılar":"0",
                            "Köklü Sayılar":"0",
                            "Çarpanlara Ayırma":"0",
                            "Oran Orantı":"0",
                            "Denklem Çözme":"0",
                            "Problemler":"0",
                            "Kümeler":"0",
                            "Kartezyen Çarpım":"0",
                            "Mantık":"0",
                            "Fonskiyonlar":"0",
                            "Polinomlar":"0",
                            "2. Dereceden Denklemler":"0",
                            "Permütasyon ve Kombinasyon":"0",
                            "Binom ve Olasılık":"0",
                            "İstatistik":"0",
                            "Karmaşık Sayılar":"0",
                            "2. Dereceden Eşitsizlikler":"0",
                            "Parabol":"0",
                            "Trigonometri":"0",
                            "Logaritma":"0",
                            "Diziler":"0",
                            "Limit":"0",
                            "Türev":"0",
                            "İntegral":"0"
                        ],
                        "AYT Geometri Süre" : [
                            "Temel Kavramlar":"00:00:00",
                            "Doğruda Açılar":"00:00:00",
                            "Üçgende Açılar":"00:00:00",
                            "Dik Üçgen":"00:00:00",
                            "İkizkenar Üçgen":"00:00:00",
                            "Eşkenar Üçgen":"00:00:00",
                            "Açıortay":"00:00:00",
                            "Kenarortay":"00:00:00",
                            "Üçgende Alan":"00:00:00",
                            "Üçgende Benzerlik":"00:00:00",
                            "Açı Kenar Bağıntıları":"00:00:00",
                            "Çokgenler":"00:00:00",
                            "Dörtgenler":"00:00:00",
                            "Deltoid":"00:00:00",
                            "Paralelkenar":"00:00:00",
                            "Eşkenar Dörtgen":"00:00:00",
                            "Dikdörtgen":"00:00:00",
                            "Kare":"00:00:00",
                            "İkizkenar":"00:00:00",
                            "Yamuk":"00:00:00",
                            "Çember ve Daire":"00:00:00",
                            "Noktanın Analitiği":"00:00:00",
                            "Doğrunun Analitiği":"00:00:00",
                            "Dönüşüm Geometrisi":"00:00:00",
                            "Dikdörtgenler Prizması":"00:00:00",
                            "Küp":"00:00:00",
                            "Silindir":"00:00:00",
                            "Piramit":"00:00:00",
                            "Koni":"00:00:00",
                            "Küre":"00:00:00",
                            "Çemberin Analitiği":"00:00:00"
                        ],
                        "AYT Geometri Soru" : [
                            "Temel Kavramlar":"0",
                            "Doğruda Açılar":"0",
                            "Üçgende Açılar":"0",
                            "Dik Üçgen":"0",
                            "İkizkenar Üçgen":"0",
                            "Eşkenar Üçgen":"0",
                            "Açıortay":"0",
                            "Kenarortay":"0",
                            "Üçgende Alan":"0",
                            "Üçgende Benzerlik":"0",
                            "Açı Kenar Bağıntıları":"0",
                            "Çokgenler":"0",
                            "Dörtgenler":"0",
                            "Deltoid":"0",
                            "Paralelkenar":"0",
                            "Eşkenar Dörtgen":"0",
                            "Dikdörtgen":"0",
                            "Kare":"0",
                            "İkizkenar":"0",
                            "Yamuk":"0",
                            "Çember ve Daire":"0",
                            "Noktanın Analitiği":"0",
                            "Doğrunun Analitiği":"0",
                            "Dönüşüm Geometrisi":"0",
                            "Dikdörtgenler Prizması":"0",
                            "Küp":"0",
                            "Silindir":"0",
                            "Piramit":"0",
                            "Koni":"0",
                            "Küre":"0",
                            "Çemberin Analitiği":"0"
                        ],
                        "AYT Geometri Switch" : [
                            "Temel Kavramlar":"0",
                            "Doğruda Açılar":"0",
                            "Üçgende Açılar":"0",
                            "Dik Üçgen":"0",
                            "İkizkenar Üçgen":"0",
                            "Eşkenar Üçgen":"0",
                            "Açıortay":"0",
                            "Kenarortay":"0",
                            "Üçgende Alan":"0",
                            "Üçgende Benzerlik":"0",
                            "Açı Kenar Bağıntıları":"0",
                            "Çokgenler":"0",
                            "Dörtgenler":"0",
                            "Deltoid":"0",
                            "Paralelkenar":"0",
                            "Eşkenar Dörtgen":"0",
                            "Dikdörtgen":"0",
                            "Kare":"0",
                            "İkizkenar":"0",
                            "Yamuk":"0",
                            "Çember ve Daire":"0",
                            "Noktanın Analitiği":"0",
                            "Doğrunun Analitiği":"0",
                            "Dönüşüm Geometrisi":"0",
                            "Dikdörtgenler Prizması":"0",
                            "Küp":"0",
                            "Silindir":"0",
                            "Piramit":"0",
                            "Koni":"0",
                            "Küre":"0",
                            "Çemberin Analitiği":"0"
                        ],
                        "AYT Fizik Süre" : [
                            "Vektörler":"00:00:00",
                            "Kuvvet, Tork ve Denge":"00:00:00",
                            "Kütle Merkezi":"00:00:00",
                            "Basit Makineler":"00:00:00",
                            "Hareket":"00:00:00",
                            "Newton’un Hareket Yasaları":"00:00:00",
                            "İş, Güç ve Enerji II":"00:00:00",
                            "Atışlar":"00:00:00",
                            "İtme ve Momentum":"00:00:00",
                            "Elektrik Alan ve Potansiyel":"00:00:00",
                            "Paralel Levhalar ve Sığa":"00:00:00",
                            "Manyetik Alan ve Manyetik Kuvvet":"00:00:00",
                            "İndüksiyon, Alternatif Akım ve Transformatörler":"00:00:00",
                            "Çembersel Hareket":"00:00:00",
                            "Kütle Çekim ve Kepler Yasaları":"00:00:00",
                            "Basit Harmonik Hareket":"00:00:00",
                            "Dalga Mekaniği ve Elektromanyetik Dalgalar":"00:00:00",
                            "Atom Modelleri":"00:00:00",
                            "Büyük Patlama ve Radyoaktivite":"00:00:00",
                            "Modern Fizik":"00:00:00",
                            "Modern Fiziğin Teknolojideki Uygulamaları":"00:00:00"
                        ],
                        "AYT Fizik Soru" : [
                            "Vektörler":"0",
                            "Kuvvet, Tork ve Denge":"0",
                            "Kütle Merkezi":"0",
                            "Basit Makineler":"0",
                            "Hareket":"0",
                            "Newton’un Hareket Yasaları":"0",
                            "İş, Güç ve Enerji II":"0",
                            "Atışlar":"0",
                            "İtme ve Momentum":"0",
                            "Elektrik Alan ve Potansiyel":"0",
                            "Paralel Levhalar ve Sığa":"0",
                            "Manyetik Alan ve Manyetik Kuvvet":"0",
                            "İndüksiyon, Alternatif Akım ve Transformatörler":"0",
                            "Çembersel Hareket":"0",
                            "Kütle Çekim ve Kepler Yasaları":"0",
                            "Basit Harmonik Hareket":"0",
                            "Dalga Mekaniği ve Elektromanyetik Dalgalar":"0",
                            "Atom Modelleri":"0",
                            "Büyük Patlama ve Radyoaktivite":"0",
                            "Modern Fizik":"0",
                            "Modern Fiziğin Teknolojideki Uygulamaları":"0"
                        ],
                        "AYT Fizik Switch" : [
                            "Vektörler":"0",
                            "Kuvvet, Tork ve Denge":"0",
                            "Kütle Merkezi":"0",
                            "Basit Makineler":"0",
                            "Hareket":"0",
                            "Newton’un Hareket Yasaları":"0",
                            "İş, Güç ve Enerji II":"0",
                            "Atışlar":"0",
                            "İtme ve Momentum":"0",
                            "Elektrik Alan ve Potansiyel":"0",
                            "Paralel Levhalar ve Sığa":"0",
                            "Manyetik Alan ve Manyetik Kuvvet":"0",
                            "İndüksiyon, Alternatif Akım ve Transformatörler":"0",
                            "Çembersel Hareket":"0",
                            "Kütle Çekim ve Kepler Yasaları":"0",
                            "Basit Harmonik Hareket":"0",
                            "Dalga Mekaniği ve Elektromanyetik Dalgalar":"0",
                            "Atom Modelleri":"0",
                            "Büyük Patlama ve Radyoaktivite":"0",
                            "Modern Fizik":"0",
                            "Modern Fiziğin Teknolojideki Uygulamaları":"0"
                        ],
                        "AYT Kimya Süre" : [
                            "Kimya Bilimi":"00:00:00",
                            "Atom ve Periyodik Sistem":"00:00:00",
                            "Kimyasal Türler Arası Etkileşimler":"00:00:00",
                            "Kimyasal Hesaplamalar":"00:00:00",
                            "Kimyanın Temel Kanunları":"00:00:00",
                            "Asit, Baz ve Tuz":"00:00:00",
                            "Maddenin Halleri":"00:00:00",
                            "Karışımlar":"00:00:00",
                            "Doğa ve Kimya":"00:00:00",
                            "Kimya Her Yerde":"00:00:00",
                            "Modern Atom Teorisi":"00:00:00",
                            "Gazlar":"00:00:00",
                            "Çözeltiler":"00:00:00",
                            "Kimyasal Tepkimelerde Enerji":"00:00:00",
                            "Kimyasal Tepkimelerde Hız":"00:00:00",
                            "Kimyasal Tepkimelerde Denge":"00:00:00",
                            "Asit Baz Dengesi":"00:00:00",
                            "Çözünürlük Dengesi":"00:00:00",
                            "Kimya ve Elektrik":"00:00:00",
                            "Karbon Kimyasına Giriş":"00:00:00",
                            "Organik Kimya":"00:00:00"
                        ],
                        "AYT Kimya Soru" : [
                            "Kimya Bilimi":"0",
                            "Atom ve Periyodik Sistem":"0",
                            "Kimyasal Türler Arası Etkileşimler":"0",
                            "Kimyasal Hesaplamalar":"0",
                            "Kimyanın Temel Kanunları":"0",
                            "Asit, Baz ve Tuz":"0",
                            "Maddenin Halleri":"0",
                            "Karışımlar":"0",
                            "Doğa ve Kimya":"0",
                            "Kimya Her Yerde":"0",
                            "Modern Atom Teorisi":"0",
                            "Gazlar":"0",
                            "Çözeltiler":"0",
                            "Kimyasal Tepkimelerde Enerji":"0",
                            "Kimyasal Tepkimelerde Hız":"0",
                            "Kimyasal Tepkimelerde Denge":"0",
                            "Asit Baz Dengesi":"0",
                            "Çözünürlük Dengesi":"0",
                            "Kimya ve Elektrik":"0",
                            "Karbon Kimyasına Giriş":"0",
                            "Organik Kimya":"0"
                        ],
                        "AYT Kimya Switch" : [
                            "Kimya Bilimi":"0",
                            "Atom ve Periyodik Sistem":"0",
                            "Kimyasal Türler Arası Etkileşimler":"0",
                            "Kimyasal Hesaplamalar":"0",
                            "Kimyanın Temel Kanunları":"0",
                            "Asit, Baz ve Tuz":"0",
                            "Maddenin Halleri":"0",
                            "Karışımlar":"0",
                            "Doğa ve Kimya":"0",
                            "Kimya Her Yerde":"0",
                            "Modern Atom Teorisi":"0",
                            "Gazlar":"0",
                            "Çözeltiler":"0",
                            "Kimyasal Tepkimelerde Enerji":"0",
                            "Kimyasal Tepkimelerde Hız":"0",
                            "Kimyasal Tepkimelerde Denge":"0",
                            "Asit Baz Dengesi":"0",
                            "Çözünürlük Dengesi":"0",
                            "Kimya ve Elektrik":"0",
                            "Karbon Kimyasına Giriş":"0",
                            "Organik Kimya":"0"
                        ],
                        "AYT Biyoloji Süre" : [
                            "Sinir Sistemi":"00:00:00",
                            "Endokrin Sistem":"00:00:00",
                            "Duyu Organları":"00:00:00",
                            "Destek ve Hareket Sistemi":"00:00:00",
                            "Sindirim Sistemi":"00:00:00",
                            "Dolaşım ve Bağışıklık Sistemi":"00:00:00",
                            "Solunum Sistemi":"00:00:00",
                            "Boşaltım Sistemi":"00:00:00",
                            "Üriner Sistem":"00:00:00",
                            "Üreme Sistemi ve Embriyonik Gelişim":"00:00:00",
                            "Komünite ve Popülasyon Ekolojisi":"00:00:00",
                            "Nükleik Asitler":"00:00:00",
                            "Genetik Şifre ve Protein Sentezi":"00:00:00",
                            "Canlılık ve Enerji":"00:00:00",
                            "Fotosentez ve Kemosentez":"00:00:00",
                            "Hücresel Solunum":"00:00:00",
                            "Bitki Biyolojisi":"00:00:00",
                            "Canlılar ve Çevre":"00:00:00"
                        ],
                        "AYT Biyoloji Soru" : [
                            "Sinir Sistemi":"0",
                            "Endokrin Sistem":"0",
                            "Duyu Organları":"0",
                            "Destek ve Hareket Sistemi":"0",
                            "Sindirim Sistemi":"0",
                            "Dolaşım ve Bağışıklık Sistemi":"0",
                            "Solunum Sistemi":"0",
                            "Boşaltım Sistemi":"0",
                            "Üriner Sistem":"0",
                            "Üreme Sistemi ve Embriyonik Gelişim":"0",
                            "Komünite ve Popülasyon Ekolojisi":"0",
                            "Nükleik Asitler":"0",
                            "Genetik Şifre ve Protein Sentezi":"0",
                            "Canlılık ve Enerji":"0",
                            "Fotosentez ve Kemosentez":"0",
                            "Hücresel Solunum":"0",
                            "Bitki Biyolojisi":"0",
                            "Canlılar ve Çevre":"0"
                        ],
                        "AYT Biyoloji Switch" : [
                            "Sinir Sistemi":"0",
                            "Endokrin Sistem":"0",
                            "Duyu Organları":"0",
                            "Destek ve Hareket Sistemi":"0",
                            "Sindirim Sistemi":"0",
                            "Dolaşım ve Bağışıklık Sistemi":"0",
                            "Solunum Sistemi":"0",
                            "Boşaltım Sistemi":"0",
                            "Üriner Sistem":"0",
                            "Üreme Sistemi ve Embriyonik Gelişim":"0",
                            "Komünite ve Popülasyon Ekolojisi":"0",
                            "Nükleik Asitler":"0",
                            "Genetik Şifre ve Protein Sentezi":"0",
                            "Canlılık ve Enerji":"0",
                            "Fotosentez ve Kemosentez":"0",
                            "Hücresel Solunum":"0",
                            "Bitki Biyolojisi":"0",
                            "Canlılar ve Çevre":"0"
                        ]
                    ] as [String : Any]
                    
                    if let userUid = Auth.auth().currentUser?.uid {
                        fireStore.collection("Users").document(userUid).setData(userDict, merge: true) { (error) in
                            if error != nil {
                                self.makeAlert(title: "Hata", message: error?.localizedDescription ?? "Bir hata oluştu. Lütfen tekrar deneyin.")
                            } else {
//                                Auth.auth().currentUser?.sendEmailVerification(completion: { (error) in
//                                    if error != nil {
//                                        print(error?.localizedDescription ?? "Error")
//                                    }
//                                })
                                self.performSegue(withIdentifier: "toTabBarControllerAfterRegister", sender: nil)
                            }
                        }
                    }
                }
            }
        } else {
            self.makeAlert(title: "Hata", message: "Lütfen tüm alanları doldurun.")
        }
    }
    
    func makeAlert(title: String, message: String) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: UIAlertController.Style.alert)
        let okButton = UIAlertAction(title: "Tamam", style: UIAlertAction.Style.default, handler: nil)
        alert.addAction(okButton)
        self.present(alert, animated: true, completion: nil)
    }
    
}
